version: '3.8'

services:
  postgres:
    image: postgres:15.3
    container_name: hackaton-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alumno
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: course-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: hackaton-pgadmin
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alumno@google.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
