services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"  
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: chat-app
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MYSQLHOST=db
      - MYSQLUSER=root
      - MYSQLPASS=root
      - MYSQLBBDD=sandbox
      - CLIENTID=${CLIENTID}
      - SECRETID=${SECRETID}
      - CALLBACKURL=${CALLBACKURL}
      - SECRET=${SECRET}
    ports:
      - '3000:3000'

volumes:
  db-data: